### ISSUE TITLE
Wrapped callbacks are not working?

### ISSUE THREAD

**Issue by nullptr128** [mbest/knockout.punches#56]
Hello! I just started to use your great library!

Unfortunately, looks like wrapped callbacks feature is not working correctly, or I misunderstood its behaviour. If all clicks etc are wrapped in function(){}, my data-bind="click: window.alert('test')" should not be called immediately after page loads? Because it alerts as soon as applyBindings goes on.

**Comment by mbest** [comment]
If you want to use that form of binding, you'll need to use the `on.*` binding: `data-bind="on.click: window.alert('test')"`.

**Comment by nkosi23** [comment]
Hello,

I am also experiencing the immediate calling of callbacks when applyBindings is executed. Simple bindings such as :  click: doSomething are executed immediately while bindings such as click: $root.doSomething aren't.

I'm dealing with an existing codebase so when I chose to introduce punches it was with the hope of avoiding modifying all the codebase. Are you saying that in order to leverage the wrappedCallback feature it it necessary to replace all the bindings with on.binding ?

I am bootstrapping punches with this :    ko.punches.wrappedCallback.enableForBinding(ko.bindingHandlers.click);

Thanks

**Comment by mbest** [comment]
@reddyBell Are you sure? Please look at your code and post the actual code that's failing.

**Comment by nkosi23** [comment]
Thanks for the swift reply, let me look into it again

**Comment by nkosi23** [comment]
The actual code is complex, but by isolating it the issue happens with code such as :

```
<div data-bind="click: login">
</div>
```

And the view model is :

```
var LoginViewModel = (function () {
LoginViewModel.prototype.login = function () {
            alert('do something');
        };
}());
```

I'm positive the issue comes from punches, this started just after I introduced the library. At first I just noticed that the validation of the login form page was fired as soon as the page was loading. Then I quickly realized that all the  callbacks defined with the syntax mentionned in my previous message were fired immediately on all of the pages.

**Comment by mbest** [comment]
Perhaps you can figure out how to reproduce here: https://jsfiddle.net/mbest/9frdbnfm/

**Comment by nkosi23** [comment]
Thanks, so you are saying this shouldn't happen ?

**Comment by nkosi23** [comment]
I'll try to reproduce it in there

**Comment by nkosi23** [comment]
Deepest apologies, punches is working fine..... A serie of unfortunate coincidences misled me. Many thanks for your help Michael and sorry again for the time spent on that.

**Comment by mbest** [comment]
No problem. I'm glad I could help.
